# Maximum tier: Pentium / 32 MB / SVGA 1024 / AWE32 + GUS + MPU-401.

[sdl]
windowresolution=original
output=opengl
fullscreen=false
autolock=false

[dosbox]
machine=svga_s3
memsize=32
nopromptfolder=true

[render]
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=pentium
cycles=fixed 100000

[sblaster]
sbtype=sb16
sbbase=220
irq=5
dma=1
hdma=5
oplmode=opl3

[gus]
gus=true
gusbase=240
gusrate=44100
gusirq=11
gusdma=3
ultradir=C:\ULTRASND

[autoexec]
@echo off
mount C "C:\Development\NetISA\hearo"
C:
SET BLASTER=A220 I5 D1 H5 P330 T6
SET ULTRASND=240,3,3,11,5
HEARO.EXE
