# Headless test of TESTDET on a Sound Blaster Pro 2 config.

[sdl]
output=surface
autolock=false
waitonerror=false

[dosbox]
machine=svga_s3
memsize=4
nopromptfolder=true

[cpu]
core=auto
cputype=386
cycles=fixed 25000

[render]
scaler=none

[sblaster]
sbtype=sbpro2
sbbase=220
irq=5
dma=1
oplmode=opl3

[gus]
gus=false

[autoexec]
mount C "C:\Development\NetISA\hearo"
C:
SET BLASTER=A220 I5 D1 T4
TESTDET.EXE > C:\TESTDET.OUT
EXIT
