[sdl]
output=surface
autolock=false
[dosbox]
machine=svga_s3
memsize=16
nopromptfolder=true
[cpu]
core=auto
cputype=pentium
cycles=fixed 50000
[sblaster]
sbtype=sb16
sbbase=220
irq=5
dma=1
hdma=5
oplmode=opl3
[autoexec]
mount C "C:\Development\NetISA\hearo"
C:
SET BLASTER=A220 I5 D1 H5 P330 T6
ECHO START > C:\XMQ.OUT
TESTPLAY.EXE /N /T1 data\TONE.XM >> C:\XMQ.OUT
ECHO DONE ec=%ERRORLEVEL% >> C:\XMQ.OUT
EXIT
