[sdl]
output=opengl
autolock=false

[dosbox]
machine=svga_s3
memsize=16
nopromptfolder=true

[cpu]
core=auto
cputype=486
cycles=fixed 50000

[render]
aspect=true

[sblaster]
sbtype=sb16
sbbase=220
irq=5
dma=1
hdma=5
oplmode=opl3

[gus]
gus=true
gusbase=240
gusrate=44100
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[autoexec]
@echo off
mount C "C:\Development\NetISA\hearo"
C:
SET BLASTER=A220 I5 D1 H5 P330 T6
SET ULTRASND=240,3,3,5,5
HEARO.EXE
rem Stay open so we can capture what HEARO drew before EXIT
