# Headless test of TESTDET on a Pentium config.

[sdl]
output=surface
autolock=false
waitonerror=false

[dosbox]
machine=svga_s3
memsize=32
nopromptfolder=true

[cpu]
core=auto
cputype=pentium
cycles=fixed 100000

[render]
scaler=none

[serial]
serial1=disabled
serial2=disabled

[parallel]
parallel1=disabled

[autoexec]
mount C "C:\Development\NetISA\hearo"
C:
SET BLASTER=A220 I5 D1 H5 P330 T6
SET ULTRASND=240,3,3,11,5
TESTDET.EXE > C:\TESTDET.OUT
EXIT
