/*
 * config/config.c - INI-style HEARO.CFG reader/writer.
 * Copyright (c) 2026 Tony Atkins. MIT License.
 *
 * Sections supported: [hardware], [ui], [playback], [recognition], [advanced].
 * Keys not in a known section are still preserved on save under [advanced].
 *
 * The store is a flat array of (section,key,value). Saves rewrite the file in
 * the order keys were last set, with section headers inserted on changes. The
 * v1.0 size limits are generous (256 keys, 64 byte values).
 */
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#define MAX_KEYS 256

typedef struct {
    char section[16];
    char key[24];
    char value[64];
} cfg_kv_t;

static cfg_kv_t store[MAX_KEYS];
static u16 store_count = 0;

static cfg_kv_t *find_kv(const char *section, const char *key)
{
    u16 i;
    for (i = 0; i < store_count; i++) {
        if (strcmp(store[i].section, section) == 0 &&
            strcmp(store[i].key, key) == 0) return &store[i];
    }
    return 0;
}

hbool config_load(const char *path)
{
    FILE *f;
    char line[160];
    char section[16] = "hardware";
    store_count = 0;
    f = fopen(path, "r");
    if (!f) return HFALSE;
    while (fgets(line, sizeof(line), f)) {
        u16 n = (u16)strlen(line);
        char *eq;
        while (n > 0 && (line[n - 1] == '\n' || line[n - 1] == '\r' || line[n - 1] == ' ')) line[--n] = '\0';
        if (n == 0 || line[0] == '#' || line[0] == ';') continue;
        if (line[0] == '[') {
            char *close = strchr(line, ']');
            if (close) {
                u16 sl = (u16)(close - line - 1);
                if (sl >= sizeof(section)) sl = sizeof(section) - 1;
                memcpy(section, line + 1, sl);
                section[sl] = '\0';
            }
            continue;
        }
        eq = strchr(line, '=');
        if (!eq) continue;
        if (store_count >= MAX_KEYS) break;
        {
            cfg_kv_t *kv = &store[store_count++];
            u16 klen = (u16)(eq - line);
            while (klen > 0 && line[klen - 1] == ' ') klen--;
            if (klen >= sizeof(kv->key)) klen = sizeof(kv->key) - 1;
            memcpy(kv->key, line, klen);
            kv->key[klen] = '\0';
            strncpy(kv->section, section, sizeof(kv->section) - 1);
            kv->section[sizeof(kv->section) - 1] = '\0';
            {
                const char *val = eq + 1;
                while (*val == ' ' || *val == '\t') val++;
                strncpy(kv->value, val, sizeof(kv->value) - 1);
                kv->value[sizeof(kv->value) - 1] = '\0';
            }
        }
    }
    fclose(f);
    return HTRUE;
}

hbool config_save(const char *path)
{
    FILE *f = fopen(path, "w");
    char current[16] = "";
    u16 i;
    if (!f) return HFALSE;
    fprintf(f, "# HEARO.CFG - generated by HEARO " HEARO_VER_STRING "\n\n");
    for (i = 0; i < store_count; i++) {
        if (strcmp(current, store[i].section) != 0) {
            strcpy(current, store[i].section);
            fprintf(f, "\n[%s]\n", current);
        }
        fprintf(f, "%s=%s\n", store[i].key, store[i].value);
    }
    fclose(f);
    return HTRUE;
}

const char *config_get(const char *section, const char *key)
{
    cfg_kv_t *kv = find_kv(section, key);
    return kv ? kv->value : 0;
}

void config_set(const char *section, const char *key, const char *val)
{
    cfg_kv_t *kv = find_kv(section, key);
    if (!kv) {
        if (store_count >= MAX_KEYS) return;
        kv = &store[store_count++];
        strncpy(kv->section, section, sizeof(kv->section) - 1);
        kv->section[sizeof(kv->section) - 1] = '\0';
        strncpy(kv->key, key, sizeof(kv->key) - 1);
        kv->key[sizeof(kv->key) - 1] = '\0';
    }
    strncpy(kv->value, val, sizeof(kv->value) - 1);
    kv->value[sizeof(kv->value) - 1] = '\0';
}

s32 config_get_int(const char *section, const char *key, s32 def)
{
    const char *v = config_get(section, key);
    if (!v || !*v) return def;
    return (s32)strtol(v, 0, 0);
}

hbool config_get_bool(const char *section, const char *key, hbool def)
{
    const char *v = config_get(section, key);
    if (!v || !*v) return def;
    if (v[0] == '1' || v[0] == 'T' || v[0] == 't' || v[0] == 'Y' || v[0] == 'y') return HTRUE;
    return HFALSE;
}
