/*
 * config.c - CHIME.CFG INI reader and writer.
 * Copyright (c) 2026 Tony Atkins. MIT License.
 *
 * Sections supported:
 *   [server]
 *     host=time.cloudflare.com
 *     path=/
 *     port=443
 *     mode=https-head
 *
 *   [clock]
 *     tz_offset_minutes=0
 *     auto_write=0
 *
 *   [advanced]
 *     verbose=0
 *
 * Anything else is ignored. The grammar is the same as HEARO.CFG so a future
 * shared parser can replace both.
 */
#include "config.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static const char *trim_left(const char *s) {
    while (*s == ' ' || *s == '\t') s++;
    return s;
}

static cbool key_matches(const char *line, const char *key)
{
    u16 i = 0;
    while (key[i] && line[i] && line[i] != '=') {
        char a = line[i], b = key[i];
        if (a >= 'A' && a <= 'Z') a = (char)(a + 32);
        if (b >= 'A' && b <= 'Z') b = (char)(b + 32);
        if (a != b) return CFALSE;
        i++;
    }
    return (key[i] == '\0' && (line[i] == '=' || line[i] == ' ')) ? CTRUE : CFALSE;
}

cbool config_load(const char *path, chime_config_t *cfg)
{
    FILE *f;
    char line[160];
    char section[16] = "";
    if (!path || !cfg) return CFALSE;
    f = fopen(path, "r");
    if (!f) return CFALSE;
    while (fgets(line, sizeof(line), f)) {
        u16 n = (u16)strlen(line);
        const char *value;
        char *eq;
        while (n > 0 && (line[n - 1] == '\n' || line[n - 1] == '\r' || line[n - 1] == ' ')) line[--n] = '\0';
        if (n == 0 || line[0] == '#' || line[0] == ';') continue;
        if (line[0] == '[') {
            char *close = strchr(line, ']');
            if (close) {
                u16 sl = (u16)(close - line - 1);
                if (sl >= sizeof(section)) sl = sizeof(section) - 1;
                memcpy(section, line + 1, sl);
                section[sl] = '\0';
            }
            continue;
        }
        eq = strchr(line, '=');
        if (!eq) continue;
        value = trim_left(eq + 1);

        if (strcmp(section, "server") == 0) {
            if (key_matches(line, "host")) {
                strncpy(cfg->server, value, sizeof(cfg->server) - 1);
                cfg->server[sizeof(cfg->server) - 1] = '\0';
            } else if (key_matches(line, "path")) {
                strncpy(cfg->path, value, sizeof(cfg->path) - 1);
                cfg->path[sizeof(cfg->path) - 1] = '\0';
            } else if (key_matches(line, "port")) {
                cfg->port = (u16)atoi(value);
            } else if (key_matches(line, "mode")) {
                if (strstr(value, "json"))      cfg->mode = TS_HTTPS_JSON;
                else if (strstr(value, "http-head")) cfg->mode = TS_HTTP_HEAD;
                else if (strstr(value, "stub")) cfg->mode = TS_STUB;
                else                            cfg->mode = TS_HTTPS_HEAD;
            }
        } else if (strcmp(section, "clock") == 0) {
            if (key_matches(line, "tz_offset_minutes")) cfg->tz_offset_minutes = (s16)atoi(value);
            else if (key_matches(line, "auto_write"))   cfg->auto_write = atoi(value) ? CTRUE : CFALSE;
        } else if (strcmp(section, "advanced") == 0) {
            if (key_matches(line, "verbose")) cfg->verbose = atoi(value) ? CTRUE : CFALSE;
        }
    }
    fclose(f);
    return CTRUE;
}

cbool config_save(const char *path, const chime_config_t *cfg)
{
    FILE *f;
    if (!path || !cfg) return CFALSE;
    f = fopen(path, "w");
    if (!f) return CFALSE;
    fprintf(f, "# CHIME.CFG - generated by CHIME %s\n\n", CHIME_VER_STRING);
    fprintf(f, "[server]\n");
    fprintf(f, "host=%s\n", cfg->server);
    fprintf(f, "path=%s\n", cfg->path);
    fprintf(f, "port=%u\n", cfg->port);
    fprintf(f, "mode=%s\n",
            cfg->mode == TS_HTTPS_JSON ? "https-json" :
            cfg->mode == TS_HTTP_HEAD  ? "http-head"  :
            cfg->mode == TS_STUB       ? "stub"       : "https-head");
    fprintf(f, "\n[clock]\n");
    fprintf(f, "tz_offset_minutes=%d\n", cfg->tz_offset_minutes);
    fprintf(f, "auto_write=%d\n", cfg->auto_write ? 1 : 0);
    fprintf(f, "\n[advanced]\n");
    fprintf(f, "verbose=%d\n", cfg->verbose ? 1 : 0);
    fclose(f);
    return CTRUE;
}
